#!/usr/bin/env python3
"""Create the auditable P01 CoffeeFabric-Syn Blender scene.

Run with Blender, for example:
  blender --background --python generate_blender_scene.py -- --output DIR

All geometry and materials are generated by this script. No third-party assets are used.
"""

import argparse
import hashlib
import json
import math
import random
import struct
import sys
from pathlib import Path

import bpy
from mathutils import Matrix, Vector


SCHEMA = "coffee-fabric-syn-v1"
SCENE_ID = "P01_flat_low_occlusion_v4_photoreal_attempt"
# Slightly irregular row layout derived qualitatively from project-owned field references.
# Coordinates are authored parameters, not measurements copied from the photographs.
FABRIC_PLANTS = [
    (-1.75, -2.55), (0.02, -2.48), (1.72, -2.58),
    (-1.68, -0.86), (0.08, -0.78), (1.78, -0.91),
    (-1.76, 0.84), (-0.04, 0.91), (1.69, 0.78),
    (-1.71, 2.52), (0.06, 2.44), (1.76, 2.55),
]


def arguments():
    argv = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    parser.add_argument("--seed", type=int, default=101)
    parser.add_argument("--preview-resolution", type=int, default=640)
    parser.add_argument("--preview-samples", type=int, default=48)
    parser.add_argument("--views", type=int, default=48)
    parser.add_argument("--dataset-version", choices=("v6", "v7"), default="v6")
    parser.add_argument("--engine", choices=("BLENDER_EEVEE", "CYCLES"), default="BLENDER_EEVEE")
    parser.add_argument("--skip-render", action="store_true", help="Rebuild/export deterministically while retaining existing previews")
    parser.add_argument("--coffee-asset", help="Downloaded CC-licensed .glb/.gltf/.fbx/.obj file or extracted directory")
    parser.add_argument("--asset-title", default="A coffee tree")
    parser.add_argument("--asset-author", default="rvezy")
    parser.add_argument("--asset-license", default="CC BY")
    parser.add_argument("--asset-url", default="https://sketchfab.com/3d-models/a-coffee-tree-045dba854c8d4b9e8a5dff2d18892df1")
    parser.add_argument("--asset-up-axis", choices=("X", "Y", "Z"), default="Z")
    parser.add_argument("--asset-exclude-materials", default="Cobblestone",
                        help="Comma-separated imported material names to omit, e.g. an asset display base")
    parser.add_argument("--render-dataset", action="store_true", help="Render every train/test RGB view")
    parser.add_argument("--dataset-resolution", type=int, default=800)
    parser.add_argument("--dataset-samples", type=int, default=48)
    return parser.parse_args(argv)


def reset_scene():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for block in (bpy.data.meshes, bpy.data.curves, bpy.data.materials, bpy.data.cameras, bpy.data.lights):
        # Orphaned blocks from Blender's default scene are safe to remove here.
        for item in list(block):
            if item.users == 0:
                block.remove(item)


def resolve_asset(path_text):
    path = Path(path_text).expanduser().resolve()
    if path.is_file():
        return path
    if not path.is_dir():
        raise FileNotFoundError(f"Coffee asset does not exist: {path}")
    candidates = []
    for suffix in ("*.glb", "*.gltf", "*.fbx", "*.obj"):
        candidates.extend(sorted(path.rglob(suffix)))
    if not candidates:
        raise FileNotFoundError(f"No .glb/.gltf/.fbx/.obj found under {path}")
    return candidates[0]


def import_asset(path):
    before = set(bpy.data.objects)
    suffix = path.suffix.lower()
    if suffix in (".glb", ".gltf"):
        bpy.ops.import_scene.gltf(filepath=str(path))
    elif suffix == ".fbx":
        bpy.ops.import_scene.fbx(filepath=str(path))
    elif suffix == ".obj":
        bpy.ops.wm.obj_import(filepath=str(path))
    else:
        raise ValueError(f"Unsupported coffee asset format: {suffix}")
    imported = [obj for obj in bpy.data.objects if obj not in before and obj.type == "MESH"]
    if not imported:
        raise RuntimeError(f"Coffee asset contains no mesh objects: {path}")
    # Preserve evaluated world transforms and flatten imported hierarchy for robust instancing.
    for obj in imported:
        world = obj.matrix_world.copy()
        obj.parent = None
        obj.matrix_world = world
    return imported


def tune_external_coffee_materials(objects):
    """Lift dense foliage shadows while retaining the source geometry and material identity."""
    seen = set()
    for obj in objects:
        for slot in obj.material_slots:
            mat = slot.material
            if not mat or mat in seen or not mat.use_nodes:
                continue
            seen.add(mat)
            bsdf = next((node for node in mat.node_tree.nodes if node.type == "BSDF_PRINCIPLED"), None)
            if not bsdf:
                continue
            name = mat.name.casefold()
            if "leaf" in name:
                green = (0.022, 0.19, 0.035, 1.0)
                bsdf.inputs["Base Color"].default_value = green
                bsdf.inputs["Roughness"].default_value = 0.52
                if "Emission Color" in bsdf.inputs:
                    bsdf.inputs["Emission Color"].default_value = (0.006, 0.035, 0.008, 1.0)
                    bsdf.inputs["Emission Strength"].default_value = 0.06
                if "Subsurface Weight" in bsdf.inputs:
                    bsdf.inputs["Subsurface Weight"].default_value = 0.025
            elif "metamer" in name:
                bsdf.inputs["Base Color"].default_value = (0.11, 0.055, 0.012, 1.0)
                bsdf.inputs["Roughness"].default_value = 0.68


def instantiate_external_coffee(asset_path, positions, rng, up_axis="Z", base_z=-0.09, exclude_materials=()):
    imported = import_asset(asset_path)
    excluded_names = {name.strip().casefold() for name in exclude_materials if name.strip()}
    sources, excluded = [], []
    for obj in imported:
        names = {slot.material.name.casefold() for slot in obj.material_slots if slot.material}
        (excluded if names & excluded_names else sources).append(obj)
    if not sources:
        raise RuntimeError("All imported meshes were excluded by --asset-exclude-materials")
    for obj in excluded:
        bpy.data.objects.remove(obj, do_unlink=True)
    tune_external_coffee_materials(sources)
    alignment = {
        "X": Matrix.Rotation(math.radians(-90), 4, "Y"),
        "Y": Matrix.Rotation(math.radians(90), 4, "X"),
        "Z": Matrix.Identity(4),
    }[up_axis]
    for source in sources:
        source.matrix_world = alignment @ source.matrix_world
    corners = [obj.matrix_world @ Vector(corner) for obj in sources for corner in obj.bound_box]
    lower = Vector((min(p.x for p in corners), min(p.y for p in corners), min(p.z for p in corners)))
    upper = Vector((max(p.x for p in corners), max(p.y for p in corners), max(p.z for p in corners)))
    height = upper.z - lower.z
    if height <= 1e-6:
        raise RuntimeError("Imported coffee asset has invalid zero height")
    base_center = Vector(((lower.x + upper.x) / 2, (lower.y + upper.y) / 2, lower.z))
    instance_count = 0
    for index, (x, y) in enumerate(positions):
        target_height = rng.uniform(0.48, 0.72)
        uniform_scale = target_height / height
        rotation = rng.uniform(0, math.tau)
        placement = (Matrix.Translation(Vector((x, y, base_z))) @
                     Matrix.Rotation(rotation, 4, "Z") @
                     Matrix.Scale(uniform_scale, 4) @
                     Matrix.Translation(-base_center))
        for source in sources:
            clone = source.copy()
            clone.data = source.data
            clone.name = f"licensed_coffee_{index:02d}_{source.name}"
            bpy.context.collection.objects.link(clone)
            clone.matrix_world = placement @ source.matrix_world
            clone["asset_instance"] = index
            instance_count += 1
    for source in sources:
        bpy.data.objects.remove(source, do_unlink=True)
    return {"source_meshes": len(sources), "instanced_objects": instance_count, "source_height": height}


def material(name, color, roughness=0.6, metallic=0.0):
    mat = bpy.data.materials.new(name)
    mat.diffuse_color = (*color, 1.0)
    mat.use_nodes = True
    bsdf = next((node for node in mat.node_tree.nodes if node.type == "BSDF_PRINCIPLED"), None)
    if bsdf is None:
        bsdf = mat.node_tree.nodes.new("ShaderNodeBsdfPrincipled")
        output = next((node for node in mat.node_tree.nodes if node.type == "OUTPUT_MATERIAL"), None)
        if output is None:
            output = mat.node_tree.nodes.new("ShaderNodeOutputMaterial")
        mat.node_tree.links.new(bsdf.outputs["BSDF"], output.inputs["Surface"])
    bsdf.inputs["Base Color"].default_value = (*color, 1.0)
    bsdf.inputs["Roughness"].default_value = roughness
    bsdf.inputs["Metallic"].default_value = metallic
    return mat


def procedural_material(name, colors, roughness, noise_scale, bump_strength):
    """Project-authored PBR-like material built only from Blender procedural nodes."""
    mat = material(name, colors[0], roughness)
    nodes, links = mat.node_tree.nodes, mat.node_tree.links
    bsdf = next(node for node in nodes if node.type == "BSDF_PRINCIPLED")
    noise = nodes.new("ShaderNodeTexNoise")
    noise.inputs["Scale"].default_value = noise_scale
    noise.inputs["Detail"].default_value = 5.0
    noise.inputs["Roughness"].default_value = 0.72
    ramp = nodes.new("ShaderNodeValToRGB")
    ramp.color_ramp.elements[0].color = (*colors[0], 1.0)
    ramp.color_ramp.elements[1].color = (*colors[1], 1.0)
    bump = nodes.new("ShaderNodeBump")
    bump.inputs["Strength"].default_value = bump_strength
    bump.inputs["Distance"].default_value = 0.075
    links.new(noise.outputs["Fac"], ramp.inputs["Fac"])
    links.new(ramp.outputs["Color"], bsdf.inputs["Base Color"])
    links.new(noise.outputs["Fac"], bump.inputs["Height"])
    links.new(bump.outputs["Normal"], bsdf.inputs["Normal"])
    return mat


def cube(name, location, scale, mat, bevel=0.0):
    bpy.ops.mesh.primitive_cube_add(location=location)
    obj = bpy.context.object
    obj.name = name
    obj.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    if bevel:
        mod = obj.modifiers.new("small_edge_rounding", "BEVEL")
        mod.width = bevel
        mod.segments = 2
    obj.data.materials.append(mat)
    return obj


def cylinder_between(name, a, b, radius, mat, vertices=10):
    a, b = Vector(a), Vector(b)
    delta = b - a
    bpy.ops.mesh.primitive_cylinder_add(vertices=vertices, radius=radius, depth=delta.length, location=(a + b) / 2)
    obj = bpy.context.object
    obj.name = name
    obj.rotation_mode = "QUATERNION"
    obj.rotation_quaternion = delta.to_track_quat("Z", "Y")
    obj.data.materials.append(mat)
    return obj


def leaf(name, location, rotation, scale, mat):
    # Curved elliptic-lanceolate leaf with a midrib fold and naturally drooping tip.
    segments, across = 20, 8
    verts = []
    for i in range(segments + 1):
        u = i / segments
        # The local origin is the petiole attachment; the blade grows outward only.
        xx = u
        half_width = 0.52 * math.sin(math.pi * u) ** 0.68
        for j in range(across + 1):
            v = -1.0 + 2.0 * j / across
            # Coffee references show broad blades with conspicuously undulating margins.
            margin_wave = 1.0 + 0.035 * math.sin(7.0 * math.pi * u + (0.7 if v > 0 else 0.0)) * abs(v)
            yy = half_width * v * margin_wave
            fold = 0.035 * (1.0 - abs(v)) * math.sin(math.pi * u)
            curl = -0.032 * max(0.0, u - 0.62) ** 2 / 0.38**2
            ripple = 0.012 * math.sin(5.0 * math.pi * u) * abs(v)
            verts.append((xx, yy, fold + curl + ripple))
    faces = []
    for i in range(segments):
        for j in range(across):
            a = i * (across + 1) + j
            faces.append((a, a + across + 1, a + across + 2, a + 1))
    mesh = bpy.data.meshes.new(name + "_mesh")
    mesh.from_pydata(verts, [], faces)
    mesh.materials.append(mat)
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    obj.location = location
    obj.rotation_euler = rotation
    obj.scale = scale
    for polygon in obj.data.polygons:
        polygon.use_smooth = True
    return obj


def coffee_plant(index, x, y, base_z, rng, stem_mat, leaf_mats):
    """Juvenile coffee architecture calibrated qualitatively from the field photos."""
    height = rng.uniform(0.42, 0.62)
    lean_x, lean_y = rng.uniform(-0.035, 0.035), rng.uniform(-0.035, 0.035)
    cylinder_between(f"plant_{index:02d}_trunk", (x, y, base_z),
                     (x + lean_x, y + lean_y, base_z + height), 0.011, stem_mat, 12)
    levels = rng.choice((6, 7))
    for level in range(levels):
        z = base_z + 0.11 + level * (height - 0.15) / max(1, levels - 1) + rng.uniform(-0.018, 0.018)
        # Coffee plagiotropic branches form near-opposite horizontal pairs.
        phase = level * 2.39996 + rng.uniform(-0.22, 0.22)
        for side in (-1, 1):
            angle = phase if side == 1 else phase + math.pi
            length = rng.uniform(0.18, 0.31) * (1.0 - 0.035 * level)
            end = (x + length * math.cos(angle), y + length * math.sin(angle), z + rng.uniform(-0.035, 0.018))
            cylinder_between(f"plant_{index:02d}_branch_{level}_{side}", (x, y, z), end, 0.0055, stem_mat, 8)
            for pos in (0.48, 0.76, 1.0):
                px = x + (end[0] - x) * pos
                py = y + (end[1] - y) * pos
                pz = z + (end[2] - z) * pos + rng.uniform(-0.025, 0.025)
                for leaf_side in (-1, 1):
                    yaw = angle + leaf_side * rng.uniform(0.58, 0.92)
                    leaf(
                        f"plant_{index:02d}_leaf_{level}_{side}_{pos}_{leaf_side}",
                        (px, py, pz),
                        (rng.uniform(-0.28, 0.08), leaf_side * rng.uniform(0.12, 0.30), yaw),
                        (rng.uniform(0.19, 0.29), rng.uniform(0.085, 0.115), rng.uniform(0.15, 0.22)),
                        leaf_mats[0],
                    )
    # Pale, compact apical flush seen repeatedly in the juvenile field references.
    for k in range(3):
        yaw = k * math.tau / 3 + rng.uniform(-0.18, 0.18)
        leaf(f"plant_{index:02d}_apical_{k}", (x + lean_x, y + lean_y, base_z + height),
             (rng.uniform(-0.18, -0.06), 0.0, yaw), (0.14, 0.05, 0.18), leaf_mats[1])


def terrain_mesh(mat, rng):
    n, size = 45, 10.0
    verts = []
    for iy in range(n):
        y = -size / 2 + size * iy / (n - 1)
        for ix in range(n):
            x = -size / 2 + size * ix / (n - 1)
            z = -0.14 + 0.035 * math.sin(0.8 * x) * math.cos(0.65 * y) + rng.uniform(-0.008, 0.008)
            verts.append((x, y, z))
    faces = []
    for iy in range(n - 1):
        for ix in range(n - 1):
            a = iy * n + ix
            faces.extend(((a, a + 1, a + n + 1, a + n),))
    mesh = bpy.data.meshes.new("terrain_mesh")
    mesh.from_pydata(verts, [], faces)
    mesh.materials.append(mat)
    obj = bpy.data.objects.new("terrain", mesh)
    bpy.context.collection.objects.link(obj)
    return obj


def fabric_mesh(mat):
    # Flat condition, but not mathematically perfect: independent multifrequency micro-relief.
    nx, ny, width, length = 141, 181, 5.0, 7.2
    verts = []
    for iy in range(ny):
        y = -length / 2 + length * iy / (ny - 1)
        for ix in range(nx):
            x = -width / 2 + width * ix / (nx - 1)
            z = 0.015 + 0.012 * math.sin(3.7 * x + 0.3) * math.sin(2.9 * y - 0.2)
            z += 0.005 * math.sin(9.1 * x + 1.7 * y)
            edge_distance = min(x + width / 2, width / 2 - x, y + length / 2, length / 2 - y)
            if edge_distance < 0.28:
                edge_weight = (0.28 - edge_distance) / 0.28
                z += edge_weight * (0.018 + 0.018 * math.sin(5.2 * x + 3.6 * y))
            # Small radial puckering around the independently specified planting holes.
            for hx, hy in FABRIC_PLANTS:
                distance = math.hypot(x - hx, y - hy)
                z += 0.022 * math.exp(-((distance - 0.22) / 0.10) ** 2)
            verts.append((x, y, z))
    faces = []
    for iy in range(ny - 1):
        for ix in range(nx - 1):
            a = iy * nx + ix
            cx = -width / 2 + width * (ix + 0.5) / (nx - 1)
            cy = -length / 2 + length * (iy + 0.5) / (ny - 1)
            if not any((cx - hx) ** 2 + (cy - hy) ** 2 < 0.18**2 for hx, hy in FABRIC_PLANTS):
                faces.append((a, a + 1, a + nx + 1, a + nx))
    mesh = bpy.data.meshes.new("fabric_gt_mesh")
    mesh.from_pydata(verts, [], faces)
    mesh.materials.append(mat)
    obj = bpy.data.objects.new("fabric_gt", mesh)
    bpy.context.collection.objects.link(obj)
    bevel = obj.modifiers.new("fabric_edge_softening", "SOLIDIFY")
    bevel.thickness = 0.012
    return obj


def protective_ring(index, x, y, mat):
    """Perforated-looking black root guard inspired by, but not copied from, field units."""
    # Thin rims plus a subtly corrugated vertical wall resemble the field root guards.
    bpy.ops.mesh.primitive_torus_add(major_radius=0.205, minor_radius=0.010, major_segments=64,
                                    minor_segments=8, location=(x, y, 0.055))
    ring = bpy.context.object
    ring.name = f"root_guard_ring_{index:02d}"
    ring.data.materials.append(mat)
    wall_verts, wall_faces, segments = [], [], 64
    for k in range(segments):
        angle = math.tau * k / segments
        radius = 0.205 + 0.007 * math.sin(16 * angle)
        wall_verts.extend(((x + radius * math.cos(angle), y + radius * math.sin(angle), 0.045),
                           (x + radius * math.cos(angle), y + radius * math.sin(angle), 0.115)))
    for k in range(segments):
        a, b = 2 * k, 2 * ((k + 1) % segments)
        wall_faces.append((a, b, b + 1, a + 1))
    wall_mesh = bpy.data.meshes.new(f"root_guard_wall_{index:02d}_mesh")
    wall_mesh.from_pydata(wall_verts, [], wall_faces)
    wall_mesh.materials.append(mat)
    wall = bpy.data.objects.new(f"root_guard_wall_{index:02d}", wall_mesh)
    bpy.context.collection.objects.link(wall)
    for polygon in wall.data.polygons:
        polygon.use_smooth = True
    bpy.ops.mesh.primitive_torus_add(major_radius=0.205, minor_radius=0.010, major_segments=64,
                                    minor_segments=8, location=(x, y, 0.112))
    upper = bpy.context.object
    upper.name = f"root_guard_upper_rim_{index:02d}"
    upper.data.materials.append(mat)


def scatter_ground_detail(rng, soil_mat, dry_leaf_mat):
    for i in range(90):
        x, y = rng.uniform(-3.8, 3.8), rng.uniform(-3.8, 3.8)
        if abs(x) < 2.15 and abs(y) < 3.05:
            continue
        bpy.ops.mesh.primitive_ico_sphere_add(subdivisions=1, radius=rng.uniform(0.018, 0.065), location=(x, y, -0.075))
        pebble = bpy.context.object
        pebble.name = f"authored_soil_clod_{i:03d}"
        pebble.scale = (1.0, rng.uniform(0.65, 1.25), rng.uniform(0.35, 0.75))
        pebble.data.materials.append(soil_mat)
    for i in range(32):
        x, y = rng.uniform(-3.6, 3.6), rng.uniform(-3.6, 3.6)
        if abs(x) < 1.9 and abs(y) < 2.9:
            continue
        leaf(f"authored_dry_leaf_{i:03d}", (x, y, -0.055), (0.0, rng.uniform(-0.1, 0.1), rng.uniform(0, math.tau)),
             (rng.uniform(0.07, 0.12), rng.uniform(0.04, 0.065), 0.5), dry_leaf_mat)


def scatter_weeds(rng, weed_mat):
    """Irregular weeds restricted mostly to row margins, matching the aerial context."""
    for patch in range(48):
        cx = rng.choice((-1, 1)) * rng.uniform(2.75, 4.6)
        cy = rng.uniform(-4.5, 4.5)
        for blade in range(rng.randint(5, 11)):
            x, y = cx + rng.uniform(-0.22, 0.22), cy + rng.uniform(-0.22, 0.22)
            h = rng.uniform(0.08, 0.30)
            angle = rng.uniform(0, math.tau)
            cylinder_between(f"weed_{patch:02d}_{blade:02d}", (x, y, -0.08),
                             (x + 0.05 * math.cos(angle), y + 0.05 * math.sin(angle), -0.08 + h),
                             0.006, weed_mat, 5)


def look_at(obj, target):
    obj.rotation_euler = (Vector(target) - obj.location).to_track_quat("-Z", "Y").to_euler()


def camera_plan_v6(count, seed):
    rng = random.Random(seed + 9000)
    result = []
    for i in range(count):
        t = i / count
        side = -1 if i % 2 == 0 else 1
        y = -2.8 + 5.6 * t
        x = side * rng.uniform(2.35, 2.85)
        z = rng.uniform(1.25, 1.8)
        result.append({
            "frame": i,
            "file_path": f"images/{i:05d}",
            "position": [x, y, z],
            "look_at": [rng.uniform(-0.25, 0.25), y + rng.uniform(-0.25, 0.25), 0.35],
            "focal_length_mm": 35.0,
            "role": "test" if i % 8 == 0 else "train",
        })
    return result


def camera_plan_v7(count, seed):
    """Balanced paired trajectory with internal, two-sided held-out views."""
    if count != 96:
        raise ValueError("P01 V7 uses exactly 96 views (84 train + 12 test)")
    rng = random.Random(seed + 17000)
    stations = count // 2
    # Interior stations only. Alternating held-out sides yields 6 left + 6 right.
    test_stations = [4, 7, 11, 15, 18, 22, 26, 29, 33, 37, 40, 44]
    test_side_at = {station: (-1 if index % 2 == 0 else 1)
                    for index, station in enumerate(test_stations)}
    result = []
    frame = 0
    for station in range(stations):
        y = -3.35 + 6.70 * station / (stations - 1)
        elevated = station % 8 == 4
        for side in (-1, 1):
            x = side * (2.18 if elevated else rng.uniform(2.52, 2.76))
            z = rng.uniform(2.25, 2.55) if elevated else rng.uniform(1.48, 1.92)
            role = "test" if test_side_at.get(station) == side else "train"
            result.append({
                "frame": frame,
                "station": station,
                "side": "left" if side < 0 else "right",
                "file_path": f"images/{frame:05d}",
                "position": [x, y + rng.uniform(-0.025, 0.025), z],
                "look_at": [rng.uniform(-0.10, 0.10), y + rng.uniform(-0.10, 0.10), 0.30],
                "focal_length_mm": 30.0,
                "role": role,
                "elevated": elevated,
            })
            frame += 1
    return result


def camera_plan(count, seed, version):
    return camera_plan_v7(count, seed) if version == "v7" else camera_plan_v6(count, seed)


def write_initial_point_cloud(path, seed, count=100_000):
    """Write a deterministic field-aware initialization cloud for 3DGS."""
    rng = random.Random(seed + 23000)
    header = (
        "ply\nformat binary_little_endian 1.0\n"
        f"element vertex {count}\n"
        "property float x\nproperty float y\nproperty float z\n"
        "property float nx\nproperty float ny\nproperty float nz\n"
        "property uchar red\nproperty uchar green\nproperty uchar blue\nend_header\n"
    ).encode("ascii")
    with path.open("wb") as stream:
        stream.write(header)
        for _ in range(count):
            if rng.random() < 0.82:
                x, y = rng.uniform(-2.65, 2.65), rng.uniform(-3.80, 3.80)
                z = rng.uniform(-0.16, 0.14)
                color = (96, 91, 78) if abs(x) <= 2.5 and abs(y) <= 3.6 else (126, 78, 49)
            else:
                px, py = rng.choice(FABRIC_PLANTS)
                radius, angle = rng.uniform(0.0, 0.48), rng.uniform(0.0, math.tau)
                x, y = px + radius * math.cos(angle), py + radius * math.sin(angle)
                z = rng.uniform(0.02, 1.55)
                color = (24, rng.randint(65, 105), 30)
            stream.write(struct.pack("<ffffffBBB", x, y, z, 0.0, 0.0, 0.0, *color))


def add_camera(name, spec):
    cam_data = bpy.data.cameras.new(name + "_data")
    cam_data.lens = spec["focal_length_mm"]
    cam_data.sensor_width = 36.0
    cam = bpy.data.objects.new(name, cam_data)
    bpy.context.collection.objects.link(cam)
    cam.location = spec["position"]
    look_at(cam, spec["look_at"])
    # A newly linked object's matrix_world may remain the identity until the
    # dependency graph is evaluated.  Exported NeRF poses must reflect the
    # assigned location and rotation, not that stale identity matrix.
    bpy.context.view_layer.update()
    if spec.get("fstop"):
        cam_data.dof.use_dof = True
        cam_data.dof.focus_distance = (Vector(spec["look_at"]) - cam.location).length
        cam_data.dof.aperture_fstop = spec["fstop"]
    return cam


def blender_matrix_to_nerf(obj):
    bpy.context.view_layer.update()
    return [[float(v) for v in row] for row in obj.matrix_world]


def export_transforms(root, specs):
    angle_x = 2 * math.atan(36.0 / (2 * 35.0))
    grouped = {"train": [], "test": []}
    for spec in specs:
        cam = add_camera(f"dataset_camera_{spec['frame']:05d}", spec)
        grouped[spec["role"]].append({"file_path": spec["file_path"], "transform_matrix": blender_matrix_to_nerf(cam)})
        cam.hide_render = True
    for role, frames in grouped.items():
        payload = {"camera_angle_x": angle_x, "frames": frames}
        (root / f"transforms_{role}.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")


def render_dataset_views(scene, root, specs, resolution, samples):
    """Render the exact cameras referenced by transforms_train/test for 3DGS ingestion."""
    old_resolution = (scene.render.resolution_x, scene.render.resolution_y, scene.render.resolution_percentage)
    old_samples = scene.cycles.samples if scene.render.engine == "CYCLES" else None
    scene.render.resolution_x = resolution
    scene.render.resolution_y = resolution
    scene.render.resolution_percentage = 100
    if old_samples is not None:
        scene.cycles.samples = samples
    rendered = []
    for spec in specs:
        cam = bpy.data.objects.get(f"dataset_camera_{spec['frame']:05d}")
        if cam is None:
            raise RuntimeError(f"Missing dataset camera for frame {spec['frame']}")
        cam.hide_render = False
        scene.camera = cam
        path = root / "images" / f"{spec['frame']:05d}.png"
        scene.render.filepath = str(path)
        bpy.ops.render.render(write_still=True)
        cam.hide_render = True
        rendered.append(path)
    scene.render.resolution_x, scene.render.resolution_y, scene.render.resolution_percentage = old_resolution
    if old_samples is not None:
        scene.cycles.samples = old_samples
    (root / "render_manifest.json").write_text(json.dumps({
        "modality": "RGB", "count": len(rendered), "resolution": [resolution, resolution],
        "engine": scene.render.engine, "samples": samples if old_samples is not None else None,
        "files": [str(path.relative_to(root)) for path in rendered],
    }, indent=2), encoding="utf-8")
    return rendered


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def configure_world(scene):
    scene.world.use_nodes = True
    bg = next((node for node in scene.world.node_tree.nodes if node.type == "BACKGROUND"), None)
    if bg is None:
        bg = scene.world.node_tree.nodes.new("ShaderNodeBackground")
        output = next((node for node in scene.world.node_tree.nodes if node.type == "OUTPUT_WORLD"), None)
        if output is None:
            output = scene.world.node_tree.nodes.new("ShaderNodeOutputWorld")
        scene.world.node_tree.links.new(bg.outputs["Background"], output.inputs["Surface"])
    sky = scene.world.node_tree.nodes.new("ShaderNodeTexSky")
    sky.sky_type = "MULTIPLE_SCATTERING"
    sky.sun_elevation = math.radians(38)
    sky.sun_rotation = math.radians(128)
    sky.altitude = 850.0
    scene.world.node_tree.links.new(sky.outputs["Color"], bg.inputs["Color"])
    bg.inputs["Strength"].default_value = 0.24
    light_data = bpy.data.lights.new("sun_data", "SUN")
    light_data.energy = 2.8
    light_data.angle = math.radians(12)
    sun = bpy.data.objects.new("sun", light_data)
    bpy.context.collection.objects.link(sun)
    sun.rotation_euler = (math.radians(28), math.radians(-18), math.radians(-32))
    area_data = bpy.data.lights.new("sky_fill_data", "AREA")
    area_data.energy = 900
    area_data.shape = "DISK"
    area_data.size = 7.0
    area = bpy.data.objects.new("sky_fill", area_data)
    bpy.context.collection.objects.link(area)
    area.location = (-2.0, -1.0, 6.0)


def main():
    args = arguments()
    if args.dataset_version == "v7" and not args.coffee_asset:
        raise ValueError("P01 V7 requires the recorded licensed coffee asset")
    scene_id = ("P01_flat_low_occlusion_v7_balanced96" if args.dataset_version == "v7"
                else "P01_flat_low_occlusion_v6_paper_ready" if args.coffee_asset else SCENE_ID)
    root = Path(args.output).expanduser().resolve() / scene_id
    for folder in ("images", "bsr_masks", "depth", "fabric_depth", "normals", "ground_truth", "previews", "logs"):
        (root / folder).mkdir(parents=True, exist_ok=True)

    rng = random.Random(args.seed)
    reset_scene()
    scene = bpy.context.scene
    scene.render.engine = args.engine
    scene.render.resolution_x = args.preview_resolution
    scene.render.resolution_y = args.preview_resolution
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    scene.render.film_transparent = False
    if args.engine == "CYCLES":
        scene.cycles.samples = args.preview_samples
        scene.cycles.use_denoising = True
    else:
        scene.render.image_settings.color_mode = "RGBA"
    scene.view_settings.look = "AgX - Medium High Contrast"
    configure_world(scene)

    soil = procedural_material("authored_soil", ((0.095, 0.026, 0.008), (0.34, 0.105, 0.027)), 0.93, 5.5, 0.34)
    fabric_mat = procedural_material("authored_nonwoven_fabric", ((0.006, 0.009, 0.008), (0.035, 0.047, 0.038)), 0.86, 115.0, 0.18)
    stem = material("authored_stem", (0.14, 0.08, 0.025), 0.78)
    leaves = [procedural_material("authored_leaf_mature", ((0.004, 0.028, 0.008), (0.018, 0.115, 0.026)), 0.47, 5.0, 0.055),
              procedural_material("authored_leaf_flush", ((0.018, 0.075, 0.012), (0.055, 0.20, 0.032)), 0.50, 5.0, 0.045)]
    post_mat = material("authored_support_post", (0.31, 0.21, 0.11), 0.76)
    dry_leaf_mat = material("authored_dry_leaf", (0.24, 0.09, 0.025), 0.86)
    guard_mat = procedural_material("authored_black_root_guard", ((0.004, 0.006, 0.006), (0.028, 0.034, 0.031)), 0.72, 18.0, 0.12)
    weed_mat = material("authored_field_weeds", (0.075, 0.27, 0.045), 0.73)

    terrain_mesh(soil, rng)
    fabric = fabric_mesh(fabric_mat)
    fabric["semantic_class"] = "protective_fabric"
    fabric["is_ground_truth"] = True
    for i, x in enumerate((-2.58, 2.58)):
        for j, y in enumerate((-3.68, 3.68)):
            cube(f"support_post_{i}_{j}", (x, y, 0.11), (0.055, 0.055, 0.25), post_mat, 0.015)

    asset_record = None
    if args.coffee_asset:
        asset_path = resolve_asset(args.coffee_asset)
        excluded_materials = tuple(args.asset_exclude_materials.split(","))
        asset_stats = instantiate_external_coffee(
            asset_path, FABRIC_PLANTS, rng, args.asset_up_axis,
            exclude_materials=excluded_materials,
        )
        asset_record = {
            "title": args.asset_title, "author": args.asset_author,
            "license": args.asset_license, "source_url": args.asset_url,
            "local_source_file": asset_path.name, "source_sha256": sha256(asset_path),
            "declared_up_axis": args.asset_up_axis,
            "excluded_materials": [name.strip() for name in excluded_materials if name.strip()],
            "modifications": "metric height normalization, linked instancing, random Z rotation and scale variation",
            **asset_stats,
        }
        (root / "ASSET_ATTRIBUTION.json").write_text(json.dumps(asset_record, indent=2), encoding="utf-8")
    # Plants grow through explicit holes in the mat; sparse canopies retain low occlusion.
    for index, (x, y) in enumerate(FABRIC_PLANTS):
        if not args.coffee_asset:
            coffee_plant(index, x, y, -0.09, rng, stem, leaves)
        protective_ring(index, x, y, guard_mat)
    scatter_ground_detail(rng, soil, dry_leaf_mat)
    scatter_weeds(rng, weed_mat)

    specs = camera_plan(args.views, args.seed, args.dataset_version)
    (root / "camera_plan.json").write_text(json.dumps(specs, indent=2), encoding="utf-8")
    export_transforms(root, specs)
    if args.dataset_version == "v7":
        write_initial_point_cloud(root / "points3d.ply", args.seed)

    preview_specs = {
        "P01_paper_overview.png": {"position": [5.7, -6.6, 6.9], "look_at": [0.0, 0.0, 0.12], "focal_length_mm": 58.0, "fstop": 9.0},
        "P01_root_detail.png": {"position": [3.10, -1.85, 1.02], "look_at": [1.72, -2.58, 0.16], "focal_length_mm": 72.0, "fstop": 4.5},
        "P01_row_level.png": {"position": [0.0, -5.25, 0.68], "look_at": [0.0, 0.65, 0.22], "focal_length_mm": 65.0, "fstop": 7.1},
    }

    # Save before and after rendering, so a render interruption still leaves an inspectable scene.
    blend_path = root / f"{scene_id}.blend"
    bpy.ops.wm.save_as_mainfile(filepath=str(blend_path))
    preview_paths = []
    for index, (filename, preview_spec) in enumerate(preview_specs.items()):
        preview_cam = add_camera(f"paper_preview_camera_{index}", preview_spec)
        scene.camera = preview_cam
        scene.render.filepath = str(root / "previews" / filename)
        preview_path = root / "previews" / filename
        if not args.skip_render:
            bpy.ops.render.render(write_still=True)
        elif not preview_path.exists():
            raise FileNotFoundError(f"Cannot skip missing preview: {preview_path}")
        preview_paths.append(preview_path)
    dataset_paths = []
    if args.render_dataset:
        dataset_paths = render_dataset_views(
            scene, root, specs, args.dataset_resolution, args.dataset_samples
        )
    bpy.ops.wm.save_as_mainfile(filepath=str(blend_path))

    bpy.context.view_layer.objects.active = fabric
    fabric.select_set(True)
    bpy.ops.wm.ply_export(filepath=str(root / "ground_truth" / "fabric_mesh.ply"), export_selected_objects=True)
    fabric.select_set(False)

    metadata = {
        "schema": SCHEMA,
        "scene_id": scene_id,
        "dataset_type": "synthetic",
        "status": ("P01_v7_balanced96_trainable_candidate" if args.dataset_version == "v7"
                   else "P01_v6_paper_ready_trainable_prototype" if asset_record
                   else "P01_v4_cycles_photoreal_attempt_not_final_benchmark"),
        "seed": args.seed,
        "units": "metres",
        "morphology": "flat_with_independent_multifrequency_micro_relief",
        "occlusion_level": "low",
        "vegetation_label": "licensed_external_coffee_asset" if asset_record else "procedural_juvenile_coffee_proxy_calibrated_qualitatively_from_project_field_photos_not_botanically_validated",
        "field_reference_use": "project-supplied photographs used for qualitative morphology and layout only; no pixels or textures copied",
        "asset_policy": "external asset with recorded CC attribution" if asset_record else "project-authored procedural geometry only",
        "coffee_asset": asset_record,
        "renderer": {
            "blender": bpy.app.version_string,
            "engine": args.engine,
            "samples": args.preview_samples,
            "denoising": args.engine == "CYCLES",
        },
        "camera_count": args.views,
        "camera_protocol": ("balanced_paired_84_train_12_test_internal_holdout" if args.dataset_version == "v7"
                            else "legacy_alternating_42_train_6_test"),
        "rgb_dataset_rendered": bool(dataset_paths),
        "dataset_resolution": args.dataset_resolution if dataset_paths else None,
        "license_status": "candidate_pending_project_review",
    }
    metadata_path = root / "metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    tracked = [
        blend_path,
        *preview_paths,
        root / "ground_truth" / "fabric_mesh.ply",
        root / "camera_plan.json",
        root / "transforms_train.json",
        root / "transforms_test.json",
        metadata_path,
    ]
    if args.dataset_version == "v7":
        tracked.append(root / "points3d.ply")
    if asset_record:
        tracked.append(root / "ASSET_ATTRIBUTION.json")
    if dataset_paths:
        tracked.extend([root / "render_manifest.json", *dataset_paths])
    sums = "\n".join(f"{sha256(path)}  {path.relative_to(root)}" for path in tracked) + "\n"
    (root / "SHA256SUMS").write_text(sums, encoding="utf-8")
    print(json.dumps({"scene": str(root), "previews": [str(path) for path in preview_paths], "blend": str(blend_path)}, indent=2))


if __name__ == "__main__":
    main()
